basic-config:

  name: demo-app-dev

  image: quay.io/calopezb/argo-demo-app:1.0

  replicas: 1

  port: 8080

  routeEnabled: true

  config:
    enabled: true
    data:
      APP_ENVIRONMENT: "OpenShift (demo-app-of-apps DEV)"
      APP_NAME: "Demo App - DEV"
      APP_VERSION: "1.0"

  secret:
    enabled: true
    data:
      APP_SECRET: "super secret value for DEV"