apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: quay.io/calopezb/argo-demo-app:1.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: demo-app-config-1-0
  strategy:
    blueGreen:
      activeService: demo-app
      previewService: demo-app-preview
      autoPromotionEnabled: false