---
- name: Uninstallation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Setup kubeconfig file
      ansible.builtin.include_role:
        name: demos.utils.kubeconfig

    - name: Remove demo environment on ArgoCD
      kubernetes.core.k8s:
        state: absent
        api_version: argoproj.io/v1alpha1
        kind: ApplicationSet
        namespace: openshift-gitops
        name: environment

    - name: Remove demo environment on ArgoCD
      kubernetes.core.k8s:
        state: absent
        api_version: argoproj.io/v1alpha1
        kind: Application
        namespace: openshift-gitops
        name: "{{ item }}"
      ignore_errors: true
      loop:
        - demo-argo
        - demo-helm
        - demo-kustomize
        - demo-bitwarden
        - demo-app-of-apps
        - demo-app-sets
        - demo-advanced-sync
        - demo-blue-green
        - demo-canary

    - name: Small pause # (TODO: use argoCD instead of this sh**)
      ansible.builtin.pause:
        minutes: 1

    - name: Remove Bitwarden
      ansible.builtin.include_role:
        name: demos.utils.bitwarden
      vars:
        bitwarden_operation: uninstall

    - name: Delete Demo namespaces
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ namespace.name }}"
      loop: "{{ namespaces }}"
      ignore_errors: true
      loop_control:
        loop_var: namespace

    - name: Remove Gitea Namespace
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: gitea

  vars_files:
    - vars.yaml
