version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel9:latest

dependencies:
  galaxy:
    collections:
      - name: community.general
      - name: https://github.com/clbartolome/demos.utils.git
        type: git
        version: main
options:
  package_manager_path: /usr/bin/microdnf