apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: demo-app
  sessionAffinity: None
  type: ClusterIP