apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-hello
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-hello
  template:
    metadata:
      labels:
        app: first-hello
    spec:
      containers:
      - name: sleeper
        image: registry.redhat.io/ubi9/ubi-minimal@sha256:ac61c96b93894b9169221e87718733354dd3765dd4a62b275893c7ff0d876869
        command: ["sh", "-c", "echo Sleeping...; sleep 10"]
      - name: hello
        envFrom:
        - configMapRef:
            name: config-file
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080