apiVersion: batch/v1
kind: Job
metadata:
  name: presync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: pre
        image: registry.redhat.io/ubi9/ubi-minimal@sha256:ac61c96b93894b9169221e87718733354dd3765dd4a62b275893c7ff0d876869
        command: ["sh", "-c", "echo Running PreSync Hook; sleep 5; echo Done"]
      restartPolicy: Never